### PR TITLE
updated fr.lproj

### PR DESCRIPTION
**Pull request by Balackburn**

### CODE REVIEW

**Comment by dayanch96** [comment]
What about 50-51 lines?

**Comment by Balackburn** [comment]
@dayanch96  Added line 50,51
Do you want a cleaner PR with 1 commit?

**Comment by dayanch96** [comment]
> @dayanch96 Added line 50,51 Do you want a cleaner PR with 1 commit?

Nah all good

**Comment by Balackburn** [comment]
Perfect

**Pull request merged**
